### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by mradzkii** [jvoisin/snuffleupagus#324]
Using the snuffleupagus extension on my xenforo forum, woke up to loads of these same errors

```
Fatal Error: [snuffleupagus][0.0.0.0][disabled_function] Aborted execution on call of the function 'ini_get', because its argument '$varname' content (open_basedir) matched a rule src/XF/Util/Random.php:208
```

not sure what it means
- using the default global rules
- php 7.4.4
- ubuntu 18

**Comment by jvoisin** [comment]
It means that a call of the function [`ini_get`]( https://www.php.net/manual/en/function.ini-get.php ) was aborted, because one of its aguments, here `$varname` set to `open_basedir` matched a rule, in the file `src/XF/Util/Random.php`, line 208.

This rule is in place to catch reconnaissance attempts from an attacker, `open_basedir` being an interesting security boundary. See the [related documentation]( https://snuffleupagus.readthedocs.io/config.html ) for more info.

If a had to guess, I'd say that this check is in place to see if Xenforo can access `/dev/random` or not.

**Comment by mradzkii** [comment]
means theres a exploit in xenforo? how can i solve this?

**Comment by jvoisin** [comment]
Just read the documentation and Xenforo's source code to understand what is going on.
Snuffleupagus isn't something that you can just slap on your php stack and magically be secure: some tuning might be required.

**Comment by mradzkii** [comment]
thanks, i will. whats the rule to disable this error for now?

**Comment by jvoisin** [comment]
You should be able to figure this out by reading the set of default rules, otherwise, I'm afraid that Snuffleupagus isn't really tailored for you :/
